/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author Gabriel
 */
public class PrincipalProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalProdutoView
     */
    public PrincipalProdutoView() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContador = new javax.swing.JLabel();
        txtContador = new javax.swing.JTextField();
        jmbMenuBar = new javax.swing.JMenuBar();
        jmMenu = new javax.swing.JMenu();
        jmiIncluirProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiListagemProduto = new javax.swing.JMenuItem();
        jmSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblContador.setText("Produtos Cadastrados:");

        txtContador.setEditable(false);

        jmMenu.setText("Menu");

        jmiIncluirProduto.setText("Incluir Produto");
        jmMenu.add(jmiIncluirProduto);
        jmMenu.add(jSeparator1);

        jmiListagemProduto.setText("Lista de Produtos");
        jmMenu.add(jmiListagemProduto);

        jmbMenuBar.add(jmMenu);

        jmSobre.setText("Sobre");
        jmbMenuBar.add(jmSobre);

        setJMenuBar(jmbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public JMenuItem getJmiIncluirProduto() {
        return jmiIncluirProduto;
    }
    
    public JMenuItem getJmiListagemProduto() {
        return jmiListagemProduto;
    }
    
    public JTextField getContador() {
        return txtContador;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JMenuBar jmbMenuBar;
    private javax.swing.JMenuItem jmiIncluirProduto;
    private javax.swing.JMenuItem jmiListagemProduto;
    private javax.swing.JLabel lblContador;
    private javax.swing.JTextField txtContador;
    // End of variables declaration//GEN-END:variables
}
